name: Fast API docker build push
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  push_to_release_backend:
    runs-on: ubuntu-latest
    steps:
    # Se hace este checkout para que podamos encontrar los archivos que tenemos en develop
    - uses: actions/checkout@v3

    # - name: Check tests status
    #   run: python app/test_utils.py
    - name: Git set repo url
      run: git remote set-url origin https://github.com/Daga2001/SmartMarketPlace_backend/

    - name: Git create branch release locally
      run: git branch release

    - name: Git checkout release
      run: git checkout release 

    - name: Git config username
      run: git config --global user.email '${{secrets.GIT_EMAIL}}'

    - name: Git config password
      run: git config --global user.name '${{secrets.GIT_NAME}}'

    - name: Git config pull
    run: git config pull.rebase true

    - name: Git pull release
      run: git pull origin release 

    - name: Git push 
      run: git push -u origin release
  