name: Develop to main Workflow
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  push_to_main_backend:
    runs-on: ubuntu-latest
    steps:
    # Se hace este checkout para que podamos encontrar los archivos que tenemos en develop
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Check tests status
    #   run: python app/test_utils.py
    - name: Git set repo url
      run: git remote set-url origin https://github.com/Daga2001/SmartMarketPlace_backend/

    # - name: Git create branch main locally
    #   run: git branch main

    - name: Git checkout main
      run: git checkout main 

    - name: Git config username
      run: git config --global user.email '${{secrets.GIT_EMAIL}}'

    - name: Git config password
      run: git config --global user.name '${{secrets.GIT_NAME}}'

    - name: Git merge with develop
      run: git merge develop

    - name: Git push 
      run: git push origin main
  